# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: gulimall-ware
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_wms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
server:
  port: 11000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl